#!/usr/bin/env ruby

$LOAD_PATH.unshift File.expand_path("../lib", __dir__)

require 'mercenary'
require 'repotube'

Mercenary.program(:repotube) do |p|

  p.version RepoTube::VERSION
  p.description "YouTube time-marked URLs from Git commit timestamps"
  p.syntax "repotube [options] <youtube short URL>"
  p.option "start", "-s SECONDS", "--start SECONDS", 'Set the timestamp for the first commit; defaults to 0'
  p.option "offset", "-o SECONDS", "--offset SECONDS", "Set the offset, from the start of the video, for the first commit;\n                           defaults to 0"
  p.option "first", "-f HASH", "--first HASH", "Set the hash of the first commit in the video"
  p.option "last", "-l HASH", "--last HASH", "Set the hash of the last commit in the video"
  p.option "remote", "-r USERNAME/REPO", "--remote USERNAME/REPO", "Set the remote repo path on GitHub; auto-detected if repo has a remote"

  p.action do |args, options|
    thing = RepoTube::Program.new(args,options)
    if thing.is_repo?
      thing.process_commits
      thing.output_index
      #puts thing.discover_remote
      thing.output_readme
    else
      puts "Not a Git repo!"
      abort
    end
  end

end
